http:
  routers:
    homeassistant:
      entryPoints:
        - websecure
      rule: Host(`home.{{ env "LOCAL_DOMAIN_NAME" }}`)
      middlewares:
        - local-network
      tls:
        certResolver: cloudflare
      service: homeassistant
  
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.101:8123"

  middlewares:
    local-network:
      ipAllowList:
        sourceRange:
          - "192.168.1.0/24" # From Home
          - "172.20.0.0/24" # From VPN
 